Repository riyenas0925/Sejong_Track_Management, pull requests merged in 2019-11, with the labels that each got.

#63 CLN : trackAll cleanUp, 무인기 트랙을 위해 심화교과를 위해 DTO에 추가
  src/main/java/kr/ac/sejong/dto/TrackAllViewDto.java
  src/main/resources/mappers/trackAllMapper.xml
  src/main/webapp/WEB-INF/views/trackAll.jsp
  src/main/webapp/resources/track_js/select.js
Labels: cleanup

#68 CLN,TST : Univ, Track, Subject Entitiy 연관관계 수정 및 CRUD 테스트 코드 작성
  src/main/java/kr/ac/sejong/domain/Rule.java
  src/main/java/kr/ac/sejong/domain/Subject.java
  src/main/java/kr/ac/sejong/domain/Track.java
  src/main/java/kr/ac/sejong/domain/TrackLog.java
  src/main/java/kr/ac/sejong/domain/TrackSubject.java
  src/main/java/kr/ac/sejong/domain/Univ.java
  src/main/java/kr/ac/sejong/persistence/SubjectRepository.java
  src/main/java/kr/ac/sejong/persistence/TrackSubjectRepository.java
  src/test/kr/ac/sejong/RuleTest.java
  src/test/kr/ac/sejong/SubjectTest.java
  src/test/kr/ac/sejong/TrackSubjectTest.java
  src/test/kr/ac/sejong/TrackTest.java
  src/test/kr/ac/sejong/UnivTest.java
Labels: cleanup

#74 Update README.md
  README.md
Labels: doc

#81 [#76] adminLTE적용, head분리
  README.files/colorschememapping.xml
  README.files/filelist.xml
  README.files/themedata.thmx
  README.md
  src/main/java/kr/ac/sejong/controller/MemberController.java
  src/main/webapp/WEB-INF/views/exception.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/include/head-color.jsp
  src/main/webapp/WEB-INF/views/include/head.jsp
  src/main/webapp/WEB-INF/views/include/main-header.jsp
  src/main/webapp/WEB-INF/views/include/plugins.jsp
  src/main/webapp/WEB-INF/views/joinView.jsp
  src/main/webapp/WEB-INF/views/loginResult.jsp
  src/main/webapp/WEB-INF/views/loginView.jsp
  src/main/webapp/WEB-INF/views/trackAll.jsp
  src/main/webapp/WEB-INF/views/trackrule.jsp
  src/main/webapp/WEB-INF/views/uploadForm.jsp
  src/main/webapp/WEB-INF/views/uploadResult.jsp
  src/main/webapp/WEB-INF/views/visitor.jsp
  src/test/kr/ac/sejong/MemberJoinTest.java
Labels: cleanup, enhancement

#83 [#82] bug 수정
  README.files/colorschememapping.xml
  README.files/filelist.xml
  README.files/themedata.thmx
Labels: bug

#84 [bug] readme.md수정
  README.md
Labels: bug

#87 ENH : maven test를 위한 경로 변경및 설청 추가 Resolves #86
  .gitignore
  .travis.yml
  pom.xml
  src/test/java/kr/ac/sejong/DegreeTest.java
  src/test/java/kr/ac/sejong/RuleTest.java
  src/test/java/kr/ac/sejong/SubjectTest.java
  src/test/java/kr/ac/sejong/TrackSubjectTest.java
  src/test/java/kr/ac/sejong/TrackTest.java
  src/test/java/kr/ac/sejong/UnivTest.java
  src/test/kr/ac/sejong/MemberJoinTest.java
Labels: enhancement, feature

#89 CLN,TST : trackRule Clean Up,Entity CRUD Test Code #79
  doc/무인기 융합트랙 교과과정(2018년 6월 27일 개편).xlsx
  doc/트랙신청홍보포스터_2018년도2학기.pdf
  src/main/java/kr/ac/sejong/controller/TrackJudgeController.java
  src/main/java/kr/ac/sejong/domain/Degree.java
  src/main/java/kr/ac/sejong/domain/Rule.java
  src/main/java/kr/ac/sejong/dto/UnivTrackRuleDegreeJoinDto.java
  src/main/java/kr/ac/sejong/persistence/DegreeRepository.java
  src/main/java/kr/ac/sejong/persistence/RuleCustomRepository.java
  src/main/java/kr/ac/sejong/persistence/RuleRepositoryImpl.java
  src/main/java/kr/ac/sejong/persistence_old/TrackRuleDAO.java
  src/main/java/kr/ac/sejong/persistence_old/TrackRuleDAOImpl.java
  src/main/java/kr/ac/sejong/service/TrackJudgeServiceImpl.java
  src/main/java/kr/ac/sejong/service/TrackRuleService.java
  src/main/java/kr/ac/sejong/service/TrackRuleServiceImpl.java
  src/main/webapp/WEB-INF/views/trackJudge.jsp
  src/main/webapp/WEB-INF/views/trackrule.jsp
  src/main/webapp/WEB-INF/views/uploadForm.jsp
  src/main/webapp/resources/track_js/select.js
  src/test/java/kr/ac/sejong/DegreeTest.java
  src/test/java/kr/ac/sejong/RuleTest.java
  src/test/java/kr/ac/sejong/UnivTest.java
Labels: cleanup, doc

#91 BUG : MySQL에서 한글 입력 오류 해결
  src/main/resources/data.sql
Labels: bug

#92 Update README.md
  README.md
Labels: doc, help wanted

#95 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: doc
