Repository riyenas0925/Sejong_Track_Management, pull requests merged in 2019-02, with the labels that each got.

#2 ENH:엑셀 데이터(기이수 성적.xls) 첨부 기능 및 성적 목록 표시 기능 구현
  SejongTrack/src/main/java/kr/ac/sejong/controller/UploadFormController.java
  SejongTrack/src/main/java/kr/ac/sejong/controller/UploadResultController.java
  SejongTrack/src/main/java/kr/ac/sejong/domain/subjectVO.java
  SejongTrack/src/main/webapp/WEB-INF/spring-config/applicationContext.xml
  SejongTrack/src/main/webapp/WEB-INF/views/include/main-sidebar.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/uploadForm.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/uploadResult.jsp
Labels: feature

#3 ENH:Exception 발생시 에러페이지 연결
  SejongTrack/src/main/java/kr/ac/sejong/controller/CommonExceptionAdvice.java
  SejongTrack/src/main/webapp/WEB-INF/views/exception.jsp
Labels: feature

#4 ENH,TST:트랙 이수 기준 표시 기능 추가, 기이수 과목과 트랙DB 과목 비교 기능 구현
  SejongTrack/src/main/java/kr/ac/sejong/controller/UploadResultController.java
  SejongTrack/src/main/java/kr/ac/sejong/domain/testVO.java
  SejongTrack/src/main/java/kr/ac/sejong/domain/trackSubjectVO.java
  SejongTrack/src/main/java/kr/ac/sejong/persistence/UploadResultDAO.java
  SejongTrack/src/main/java/kr/ac/sejong/persistence/UploadResultDAOImpl.java
  SejongTrack/src/main/java/kr/ac/sejong/service/UploadResultService.java
  SejongTrack/src/main/java/kr/ac/sejong/service/UploadResultServiceImpl.java
  SejongTrack/src/main/resources/mappers/uploadResultMapper.xml
  SejongTrack/src/main/webapp/WEB-INF/views/uploadResult.jsp
  SejongTrack/src/test/kr/ac/sejong/UploadResultDAOTest.java
Labels: feature

#5 ENH:기초,응용,산학과목의 이수, 미이수 표시 기능, 학점 합계 계산 기능 구현
  SejongTrack/src/main/java/kr/ac/sejong/controller/UploadFormController.java
  SejongTrack/src/main/java/kr/ac/sejong/controller/UploadResultController.java
  SejongTrack/src/main/java/kr/ac/sejong/domain/trackSubjectVO.java
  SejongTrack/src/main/java/kr/ac/sejong/persistence/UploadResultDAO.java
  SejongTrack/src/main/java/kr/ac/sejong/persistence/UploadResultDAOImpl.java
  SejongTrack/src/main/java/kr/ac/sejong/service/UploadResultService.java
  SejongTrack/src/main/java/kr/ac/sejong/service/UploadResultServiceImpl.java
  SejongTrack/src/main/resources/mappers/uploadResultMapper.xml
  SejongTrack/src/main/webapp/WEB-INF/views/uploadResult.jsp
  SejongTrack/src/test/kr/ac/sejong/UploadResultDAOTest.java
Labels: feature

#6 ENH,TST:트랙 이수 기준 Read, Delete, Create 기능 구현, TrackRuleDAOTest 테스트
  SejongTrack/src/main/java/kr/ac/sejong/controller/TrackRuleAjaxController.java
  SejongTrack/src/main/java/kr/ac/sejong/controller/TrackRuleController.java
  SejongTrack/src/main/java/kr/ac/sejong/domain/ruleVO.java
  SejongTrack/src/main/java/kr/ac/sejong/persistence/TrackRuleDAO.java
  SejongTrack/src/main/java/kr/ac/sejong/persistence/TrackRuleDAOImpl.java
  SejongTrack/src/main/java/kr/ac/sejong/service/TrackRuleService.java
  SejongTrack/src/main/java/kr/ac/sejong/service/TrackRuleServiceImpl.java
  SejongTrack/src/main/resources/SQL/tbl_rule.sql
  SejongTrack/src/main/resources/mappers/trackRuleMapper.xml
  SejongTrack/src/main/webapp/WEB-INF/views/include/main-sidebar.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/trackrule.jsp
  SejongTrack/src/test/kr/ac/sejong/TrackRuleDAOTest.java
Labels: feature

#7 CLN:파일 업로드 경로 변경, 라이브러리 버전 수정
  SejongTrack/pom.xml
  SejongTrack/src/main/webapp/WEB-INF/spring-config/applicationContext.xml
Labels: bug

#9 CLN:중복된 commons-fileupload dependency 삭제
  SejongTrack/pom.xml
Labels: bug

#8 CLN,ENH:uploadResult 구조 재배치 및 progress 추가
  SejongTrack/src/main/java/kr/ac/sejong/controller/UploadFormController.java
  SejongTrack/src/main/java/kr/ac/sejong/controller/UploadResultController.java
  SejongTrack/src/main/webapp/WEB-INF/views/include/head.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/uploadForm.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/uploadResult.jsp
Labels: feature

#10 CLN:domain.testVO 삭제, domain.ruleVO와 연결
  SejongTrack/src/main/java/kr/ac/sejong/domain/testVO.java
  SejongTrack/src/main/java/kr/ac/sejong/persistence/UploadResultDAO.java
  SejongTrack/src/main/java/kr/ac/sejong/persistence/UploadResultDAOImpl.java
  SejongTrack/src/main/java/kr/ac/sejong/service/UploadResultService.java
  SejongTrack/src/main/java/kr/ac/sejong/service/UploadResultServiceImpl.java
  SejongTrack/src/main/resources/mappers/uploadResultMapper.xml
  SejongTrack/src/main/webapp/WEB-INF/spring-config/applicationContext.xml
Labels: cleanup

#11 ENH:미이수 기초,응용 addAttribute 및 페이지 적용
  SejongTrack/src/main/java/kr/ac/sejong/controller/UploadResultController.java
  SejongTrack/src/main/webapp/WEB-INF/spring-config/applicationContext.xml
  SejongTrack/src/main/webapp/WEB-INF/views/exception.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/home.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/include/head.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/trackrule.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/uploadForm.jsp
  SejongTrack/src/main/webapp/WEB-INF/views/uploadResult.jsp
Labels: cleanup
