Repository riyenas0925/Sejong_Track_Management, pull requests merged in 2020-02, with the labels that each got.

#126 [EHN,CLN]멤버 정보 수정 페이지
  src/main/java/kr/ac/sejong/config/SpringSecurityConfig.java
  src/main/java/kr/ac/sejong/controller/MemberController_security.java
  src/main/java/kr/ac/sejong/domain/CustomUserDetails.java
  src/main/java/kr/ac/sejong/domain/MemberRole.java
  src/main/java/kr/ac/sejong/handler/CustomLoginSuccessHandler.java
  src/main/java/kr/ac/sejong/handler/CustomLogoutSuccessHandler.java
  src/main/java/kr/ac/sejong/listener/CustomHttpSessionEventPublisher.java
  src/main/java/kr/ac/sejong/service/CustomAuthenticationProvider.java
  src/main/java/kr/ac/sejong/service/CustomUserDetailsService.java
  src/main/java/kr/ac/sejong/service/MemberService.java
  src/main/java/kr/ac/sejong/service/MemberServiceImpl.java
  src/main/webapp/WEB-INF/views/exception.jsp
  src/main/webapp/WEB-INF/views/include/head.jsp
  src/main/webapp/WEB-INF/views/member/modify.jsp
  src/main/webapp/WEB-INF/views/member/pw_popup.jsp
  src/main/webapp/WEB-INF/views/trackAll.jsp
  src/main/webapp/WEB-INF/views/trackJudge.jsp
  src/main/webapp/WEB-INF/views/trackrule.jsp
  src/main/webapp/WEB-INF/views/uploadForm.jsp
Labels: bug, cleanup, feature, major

#133 ENH : TrackSubject 관리자 페이지 CRUD 구현,강의 시간표 엑셀 파일 Import 기능 구현
  src/main/java/kr/ac/sejong/config/SpringSecurityConfig.java
  src/main/java/kr/ac/sejong/domain/courseSchedule/CourseSchedule.java
  src/main/java/kr/ac/sejong/domain/courseSchedule/CourseScheduleRepository.java
  src/main/java/kr/ac/sejong/domain/subject/Subject.java
  src/main/java/kr/ac/sejong/domain/track/TrackRepositoryImpl.java
  src/main/java/kr/ac/sejong/service/CourseScheduleService.java
  src/main/java/kr/ac/sejong/service/SubjectService.java
  src/main/java/kr/ac/sejong/web/CourseScheduleApiController.java
  src/main/java/kr/ac/sejong/web/CourseScheduleController.java
  src/main/java/kr/ac/sejong/web/SubjectApiController.java
  src/main/java/kr/ac/sejong/web/dto/SubjectRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/SubjectResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/courseschedule/CourseScheduleExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/courseschedule/CourseScheduleRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/courseschedule/CourseScheduleResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/courseschedule/CourseScheduleSelectResponseDto.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/trackSubject.jsp
  src/test/java/kr/ac/sejong/CourseScheduleTest.java
  src/test/java/kr/ac/sejong/MemberTest.java
  src/test/java/kr/ac/sejong/SubjectTest.java
  src/test/java/kr/ac/sejong/TrackSubjectTest.java
  src/test/resources/testCourseSchedulel.xlsx
Labels: design, feature, major

#140 trackSubject jsp update
  src/main/java/kr/ac/sejong/web/HomeController.java
  src/main/webapp/WEB-INF/views/exception.jsp
  src/main/webapp/WEB-INF/views/include/sidebar.jsp
  src/main/webapp/WEB-INF/views/member/pw_popup.jsp
  src/main/webapp/WEB-INF/views/subject/help.jsp
  src/main/webapp/WEB-INF/views/subject/list.jsp
  src/main/webapp/WEB-INF/views/subject/preview.jsp
  src/main/webapp/WEB-INF/views/test.jsp
  src/main/webapp/WEB-INF/views/trackSubject.jsp
  src/main/webapp/resources/css/argon-dashboard.css
Labels: design, major

#144 ENH : Excel 관련 Dto 리펙토링
  src/main/java/kr/ac/sejong/service/CourseScheduleService.java
  src/main/java/kr/ac/sejong/service/TrackJudgeService.java
  src/main/java/kr/ac/sejong/service/TrackJudgeServiceImpl.java
  src/main/java/kr/ac/sejong/web/TrackJudgeController.java
  src/main/java/kr/ac/sejong/web/TrackJudgeRestController.java
  src/main/java/kr/ac/sejong/web/dto/StudentExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/SubjectRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/courseschedule/CourseScheduleExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/CourseScheduleExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/ExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/ReportCardExcelDto.java
  src/main/resources/application.properties
  src/test/java/kr/ac/sejong/SubjectTest.java
Labels: cleanup, major

#145 BUG : 회원가입 , 사용자 권한 오류 수정
  src/main/java/kr/ac/sejong/domain/CustomUserDetails.java
  src/main/webapp/WEB-INF/views/include/setting-h.jsp
  src/main/webapp/WEB-INF/views/member/joinView.jsp
  src/main/webapp/WEB-INF/views/member/modify.jsp
  src/main/webapp/WEB-INF/views/test.jsp
Labels: bug

#141 [EHN,CLN] 공지사항 게시판 crud(+멤버 서비스클래스 삭제)
  src/main/java/kr/ac/sejong/config/SpringSecurityConfig.java
  src/main/java/kr/ac/sejong/domain/notice/Notice.java
  src/main/java/kr/ac/sejong/domain/notice/NoticeRepository.java
  src/main/java/kr/ac/sejong/service/MemberService.java
  src/main/java/kr/ac/sejong/service/MemberServiceImpl.java
  src/main/java/kr/ac/sejong/service/NoticeService.java
  src/main/java/kr/ac/sejong/web/NoticeController.java
  src/main/java/kr/ac/sejong/web/NoticeRestController.java
  src/main/java/kr/ac/sejong/web/dto/NoticeRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/NoticeResponseDto.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/include/main-sidebar.jsp
  src/main/webapp/WEB-INF/views/noticeDetails.jsp
  src/main/webapp/WEB-INF/views/noticeList.jsp
  src/main/webapp/resources/track_js/notice.js
Labels: feature, help wanted, major

#148 ENH,PERF,CLN : TrackJudge Refactoring, TrackJudge 계산속도 개선
  src/main/java/kr/ac/sejong/domain/track/Track.java
  src/main/java/kr/ac/sejong/domain/trackJudge/TrackStatistic.java
  src/main/java/kr/ac/sejong/domain/tracksubject/TrackSubject.java
  src/main/java/kr/ac/sejong/domain/tracksubject/TrackSubjectCustomRepository.java
  src/main/java/kr/ac/sejong/domain/tracksubject/TrackSubjectRepository.java
  src/main/java/kr/ac/sejong/domain/tracksubject/TrackSubjectRepositoryImpl.java
  src/main/java/kr/ac/sejong/service/CourseScheduleService.java
  src/main/java/kr/ac/sejong/service/SubjectService.java
  src/main/java/kr/ac/sejong/service/TrackJudgeService.java
  src/main/java/kr/ac/sejong/service/TrackJudgeServiceImpl.java
  src/main/java/kr/ac/sejong/web/SubjectApiController.java
  src/main/java/kr/ac/sejong/web/TrackJudgeApiController.java
  src/main/java/kr/ac/sejong/web/TrackJudgeController.java
  src/main/java/kr/ac/sejong/web/TrackJudgeRestController.java
  src/main/java/kr/ac/sejong/web/dto/courseschedule/CourseScheduleRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/courseschedule/CourseScheduleResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/CourseScheduleExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/ExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/ReportCardExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/subject/SubjectDto.java
  src/main/java/kr/ac/sejong/web/dto/subject/SubjectRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/subject/SubjectResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/track/TrackRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/track/TrackResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/SubjectStatisticDto.java
  src/main/java/kr/ac/sejong/web/dto/tracksubject/TrackSubjectDto.java
  src/main/java/kr/ac/sejong/web/dto/tracksubject/TrackSubjectRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/tracksubject/TrackSubjectResponseDto.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/trackJudge.jsp
  src/test/java/kr/ac/sejong/CourseScheduleTest.java
  src/test/java/kr/ac/sejong/SubjectTest.java
  src/test/java/kr/ac/sejong/TrackJudgeTest.java
  src/test/java/kr/ac/sejong/TrackSubjectTest.java
  src/test/resources/testCardReport.xls
Labels: cleanup, feature, major

#151 ENH : trackAll 페이지 mysql query가 아닌 java stream으로 방식 변경
  src/main/java/kr/ac/sejong/config/MybatisConfig.java
  src/main/java/kr/ac/sejong/domain/track/TrackAllDAO.java
  src/main/java/kr/ac/sejong/domain/track/TrackAllDAOImpl.java
  src/main/java/kr/ac/sejong/domain/tracksubject/TrackSubject.java
  src/main/java/kr/ac/sejong/service/TrackAllService.java
  src/main/java/kr/ac/sejong/service/TrackAllServiceImpl.java
  src/main/java/kr/ac/sejong/web/TrackAllController.java
  src/main/java/kr/ac/sejong/web/TrackAllRestController.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/SubjectStatisticDto.java
  src/test/java/kr/ac/sejong/TrackAllTest.java
Labels: cleanup, feature, major

#154 [BUG, EHN,CLN] 비밀번호 변경 alert생성, Rule도메인에 commonCredit추가
  src/main/java/kr/ac/sejong/config/SpringSecurityConfig.java
  src/main/java/kr/ac/sejong/domain/member/Member.java
  src/main/java/kr/ac/sejong/domain/rule/Rule.java
  src/main/java/kr/ac/sejong/service/CustomUserDetailsService.java
  src/main/java/kr/ac/sejong/web/MemberController.java
  src/main/java/kr/ac/sejong/web/MemberController_security.java
  src/main/java/kr/ac/sejong/web/MemberRestController.java
  src/main/java/kr/ac/sejong/web/dto/MemberPwModifyDto.java
  src/main/java/kr/ac/sejong/web/handler/CustomLoginSuccessHandler.java
  src/main/java/kr/ac/sejong/web/listener/CustomHttpSessionEventPublisher.java
  src/main/webapp/WEB-INF/views/include/sidebar.jsp
  src/main/webapp/WEB-INF/views/member/changePassword.jsp
  src/main/webapp/WEB-INF/views/member/modify.jsp
  src/main/webapp/WEB-INF/views/member/pwChange.jsp
  src/main/webapp/WEB-INF/views/noticeList.jsp
  src/main/webapp/WEB-INF/views/trackRule.jsp
  src/test/java/kr/ac/sejong/RuleTest.java
Labels: bug, cleanup, feature, help wanted
