Repository riyenas0925/Sejong_Track_Management, pull requests merged in 2020-03, with the labels that each got.

#156 CLN : alert -> toastr
  src/main/webapp/WEB-INF/views/include/setting-h.jsp
  src/main/webapp/WEB-INF/views/member/modify.jsp
  src/main/webapp/WEB-INF/views/member/pwChange.jsp
  src/main/webapp/WEB-INF/views/trackSubject.jsp
Labels: cleanup

#157 ENH : trackAll jsp update
  src/main/webapp/WEB-INF/views/test.jsp
  src/main/webapp/WEB-INF/views/trackAll.jsp
Labels: design

#159 [BUG, CLN] 권한부여 버그 해결
  src/main/java/kr/ac/sejong/config/SpringSecurityConfig.java
  src/main/java/kr/ac/sejong/domain/CustomUserDetails.java
  src/main/java/kr/ac/sejong/domain/member/Member.java
  src/main/java/kr/ac/sejong/domain/member/MemberRepository.java
  src/main/java/kr/ac/sejong/domain/member/MemberRole.java
  src/main/java/kr/ac/sejong/domain/member/MemberRoleEnum.java
  src/main/java/kr/ac/sejong/domain/member/MemberRoleRepository.java
  src/main/java/kr/ac/sejong/service/CustomAuthenticationProvider.java
  src/main/java/kr/ac/sejong/service/CustomUserDetailsService.java
  src/main/java/kr/ac/sejong/web/MemberRestController.java
  src/main/java/kr/ac/sejong/web/TrackRuleController.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/noticeDetails.jsp
  src/main/webapp/WEB-INF/views/noticeList.jsp
  src/test/java/kr/ac/sejong/MemberTest.java
Labels: bug

#164 ENH : 데이터베이스 H2로 변경, application.properties 선택할수 있게 변경
  src/main/java/kr/ac/sejong/SejongtrackApplication.java
  src/main/java/kr/ac/sejong/config/ProfileConfig.java
  src/main/java/kr/ac/sejong/config/SpringSecurityConfig.java
  src/main/java/kr/ac/sejong/config/profile/DevProfileH2.java
  src/main/java/kr/ac/sejong/config/profile/DevProfileMySQL.java
  src/main/java/kr/ac/sejong/config/profile/ProductProfileMaria.java
  src/main/java/kr/ac/sejong/web/ProfileController.java
  src/main/resources/data.sql
  src/main/resources/develop/application-h2.properties
  src/main/resources/develop/application-mysql.properties
  src/main/resources/mappers/trackAllMapper.xml
  src/main/resources/production/application-maria.properties
Labels: feature

#167 BUG, CLN: 순환 참조 오류 해결, Spring Security 파일 위치 변경
  src/main/java/kr/ac/sejong/config/MultipartConfig.java
  src/main/java/kr/ac/sejong/config/SecurityConfig.java
  src/main/java/kr/ac/sejong/config/auth/CustomAuthenticationProvider.java
  src/main/java/kr/ac/sejong/config/auth/CustomHttpSessionEventPublisher.java
  src/main/java/kr/ac/sejong/config/auth/CustomLoginSuccessHandler.java
  src/main/java/kr/ac/sejong/config/auth/CustomLogoutSuccessHandler.java
  src/main/java/kr/ac/sejong/config/auth/CustomUserDetailsService.java
  src/main/java/kr/ac/sejong/web/MemberRestController.java
  src/main/java/kr/ac/sejong/web/dto/CustomUserDetails.java
  src/test/java/kr/ac/sejong/MemberTest.java
Labels: bug, major

#170 Update README.md
  README.md
Labels: doc

#172 [CLN] Domain Subject를 Course로 변경, DB 이름 변경(tbl_ prefix 제거), 컬럼 이름 변경
  src/main/java/kr/ac/sejong/domain/course/Course.java
  src/main/java/kr/ac/sejong/domain/course/CourseRepository.java
  src/main/java/kr/ac/sejong/domain/courseSchedule/CourseSchedule.java
  src/main/java/kr/ac/sejong/domain/degree/Degree.java
  src/main/java/kr/ac/sejong/domain/member/Member.java
  src/main/java/kr/ac/sejong/domain/member/MemberRole.java
  src/main/java/kr/ac/sejong/domain/notice/Notice.java
  src/main/java/kr/ac/sejong/domain/rule/Rule.java
  src/main/java/kr/ac/sejong/domain/rule/RuleRepositoryImpl.java
  src/main/java/kr/ac/sejong/domain/subject/SubjectRepository.java
  src/main/java/kr/ac/sejong/domain/track/Track.java
  src/main/java/kr/ac/sejong/domain/track/TrackCustomRepository.java
  src/main/java/kr/ac/sejong/domain/track/TrackRepositoryImpl.java
  src/main/java/kr/ac/sejong/domain/trackJudge/TrackStatistic.java
  src/main/java/kr/ac/sejong/domain/trackcourse/TrackCourse.java
  src/main/java/kr/ac/sejong/domain/trackcourse/TrackCourseCustomRepository.java
  src/main/java/kr/ac/sejong/domain/trackcourse/TrackCourseRepository.java
  src/main/java/kr/ac/sejong/domain/trackcourse/TrackCourseRepositoryImpl.java
  src/main/java/kr/ac/sejong/domain/tracksubject/TrackSubjectCustomRepository.java
  src/main/java/kr/ac/sejong/domain/tracksubject/TrackSubjectRepository.java
  src/main/java/kr/ac/sejong/domain/tracksubject/TrackSubjectRepositoryImpl.java
  src/main/java/kr/ac/sejong/domain/univ/Univ.java
  src/main/java/kr/ac/sejong/service/CourseScheduleService.java
  src/main/java/kr/ac/sejong/service/CourseService.java
  src/main/java/kr/ac/sejong/service/SubjectService.java
  src/main/java/kr/ac/sejong/service/TrackAllService.java
  src/main/java/kr/ac/sejong/service/TrackJudgeService.java
  src/main/java/kr/ac/sejong/web/CourseApiController.java
  src/main/java/kr/ac/sejong/web/TrackJudgeApiController.java
  src/main/java/kr/ac/sejong/web/dto/course/CourseDto.java
  src/main/java/kr/ac/sejong/web/dto/course/CourseRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/course/CourseResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/courseschedule/CourseScheduleRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/courseschedule/CourseScheduleResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/CourseScheduleExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/ExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/ReportCardExcelDto.java
  src/main/java/kr/ac/sejong/web/dto/subject/SubjectDto.java
  src/main/java/kr/ac/sejong/web/dto/subject/SubjectResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/track/TrackResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/trackcourse/TrackCourseDto.java
  src/main/java/kr/ac/sejong/web/dto/trackcourse/TrackCourseRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/trackcourse/TrackCourseResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/CourseStatisticDto.java
  src/main/java/kr/ac/sejong/web/dto/tracksubject/TrackSubjectDto.java
  src/main/java/kr/ac/sejong/web/dto/tracksubject/TrackSubjectRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/tracksubject/TrackSubjectResponseDto.java
  src/main/resources/data.sql
  src/test/java/kr/ac/sejong/CourseScheduleTest.java
  src/test/java/kr/ac/sejong/CourseTest.java
  src/test/java/kr/ac/sejong/DegreeTest.java
  src/test/java/kr/ac/sejong/MemberTest.java
  src/test/java/kr/ac/sejong/RuleTest.java
  src/test/java/kr/ac/sejong/TrackAllTest.java
  src/test/java/kr/ac/sejong/TrackCourseTest.java
  src/test/java/kr/ac/sejong/TrackJudgeTest.java
  src/test/java/kr/ac/sejong/TrackSubjectTest.java
  src/test/java/kr/ac/sejong/TrackTest.java
  src/test/java/kr/ac/sejong/UnivTest.java
Labels: cleanup

#174 CLN : 변경된 json data key, jsp에 적용
  src/main/webapp/WEB-INF/views/trackAll.jsp
  src/main/webapp/WEB-INF/views/trackSubject.jsp
Labels: cleanup

#176 BUG: restController에 url을 쓰지 말자.
  src/main/java/kr/ac/sejong/web/NoticeApiController.java
Labels: bug

#177 [CLN] Notice: 작성일 자료형변경(Date -> LocalDate), 글 수정일 칼럼삭제
  src/main/java/kr/ac/sejong/domain/notice/Notice.java
  src/main/java/kr/ac/sejong/web/dto/NoticeRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/NoticeResponseDto.java
  src/main/webapp/WEB-INF/views/noticeDetails.jsp
  src/main/webapp/WEB-INF/views/noticeList.jsp
Labels: cleanup

#180 [ENH,CLN] 로그인 실패시 경고문구, 로그인 시 정보는 세션에 저장하여 활용
  out/artifacts/Project_Sejong_Track_Management_Web_exploded/WEB-INF/classes/security_message.properties
  pom.xml
  src/main/java/kr/ac/sejong/config/SecurityConfig.java
  src/main/java/kr/ac/sejong/config/auth/CustomAuthenticationProvider.java
  src/main/java/kr/ac/sejong/config/auth/CustomHttpSessionEventPublisher.java
  src/main/java/kr/ac/sejong/config/auth/CustomLoginFailureHandler.java
  src/main/java/kr/ac/sejong/config/auth/CustomLoginSuccessHandler.java
  src/main/java/kr/ac/sejong/config/auth/CustomUserDetailsService.java
  src/main/java/kr/ac/sejong/domain/member/Member.java
  src/main/java/kr/ac/sejong/domain/member/MemberRepository.java
  src/main/java/kr/ac/sejong/web/MemberApiController.java
  src/main/java/kr/ac/sejong/web/dto/CustomUserDetails.java
  src/main/java/kr/ac/sejong/web/dto/member/MemberModifyInfoDto.java
  src/main/java/kr/ac/sejong/web/dto/member/MemberModifyPwDto.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/include/header.jsp
  src/main/webapp/WEB-INF/views/include/main-sidebar.jsp
  src/main/webapp/WEB-INF/views/include/sidebar.jsp
  src/main/webapp/WEB-INF/views/member/joinView.jsp
  src/main/webapp/WEB-INF/views/member/loginView.jsp
  src/main/webapp/WEB-INF/views/member/modify.jsp
  src/main/webapp/WEB-INF/views/member/pwChange.jsp
  src/main/webapp/WEB-INF/views/noticeDetails.jsp
  src/test/java/kr/ac/sejong/MemberTest.java
Labels: cleanup, feature

#183 [CLN] Controller 합치기, RestController 이름 Api prefix로 변경
  src/main/java/kr/ac/sejong/web/ApiCourseController.java
  src/main/java/kr/ac/sejong/web/ApiCourseScheduleController.java
  src/main/java/kr/ac/sejong/web/ApiMemberController.java
  src/main/java/kr/ac/sejong/web/ApiNoticeController.java
  src/main/java/kr/ac/sejong/web/ApiSelectController.java
  src/main/java/kr/ac/sejong/web/ApiTrackAllController.java
  src/main/java/kr/ac/sejong/web/ApiTrackJudgeController.java
  src/main/java/kr/ac/sejong/web/ApiTrackRuleController.java
  src/main/java/kr/ac/sejong/web/AuthController.java
  src/main/java/kr/ac/sejong/web/CourseScheduleController.java
  src/main/java/kr/ac/sejong/web/HomeController.java
  src/main/java/kr/ac/sejong/web/IndexController.java
  src/main/java/kr/ac/sejong/web/NoticeController.java
  src/main/java/kr/ac/sejong/web/ProfileController.java
  src/main/java/kr/ac/sejong/web/TrackAllController.java
  src/main/java/kr/ac/sejong/web/TrackJudgeController.java
  src/main/java/kr/ac/sejong/web/TrackRuleController.java
  src/main/java/kr/ac/sejong/web/exception/CommonExceptionAdvice.java
Labels: cleanup

#184 ENH : Swagger를 이용한 API문서 자동화
  pom.xml
  src/main/java/kr/ac/sejong/config/SecurityConfig.java
  src/main/java/kr/ac/sejong/config/StaticResourceConfig.java
  src/main/java/kr/ac/sejong/config/SwaggerConfig.java
Labels: feature

#186 Update SecurityConfig.java
  src/main/java/kr/ac/sejong/config/SecurityConfig.java
Labels: cleanup

#188 ENH : Track Rule ERD 변경, 트랙 판정 결과를 Dto를 통해 이수율, 이수학점, 트랙 분류(Pass, Non_Pass) 반환
  src/main/java/kr/ac/sejong/config/auth/CustomUserDetailsService.java
  src/main/java/kr/ac/sejong/domain/rule/Rule.java
  src/main/java/kr/ac/sejong/domain/rule/RuleCustomRepository.java
  src/main/java/kr/ac/sejong/domain/rule/RuleRepositoryImpl.java
  src/main/java/kr/ac/sejong/domain/track/TrackCustomRepository.java
  src/main/java/kr/ac/sejong/domain/track/TrackRepositoryImpl.java
  src/main/java/kr/ac/sejong/domain/trackJudge/TrackJudge.java
  src/main/java/kr/ac/sejong/service/NoticeService.java
  src/main/java/kr/ac/sejong/service/SelectListService.java
  src/main/java/kr/ac/sejong/service/SelectListServiceImpl.java
  src/main/java/kr/ac/sejong/service/TrackCourseService.java
  src/main/java/kr/ac/sejong/service/TrackJudgeService.java
  src/main/java/kr/ac/sejong/service/TrackRuleService.java
  src/main/java/kr/ac/sejong/service/TrackRuleServiceImpl.java
  src/main/java/kr/ac/sejong/web/ApiNoticeController.java
  src/main/java/kr/ac/sejong/web/ApiSelectController.java
  src/main/java/kr/ac/sejong/web/ApiTrackJudgeController.java
  src/main/java/kr/ac/sejong/web/ApiTrackRuleController.java
  src/main/java/kr/ac/sejong/web/TrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/TrackAllViewDto.java
  src/main/java/kr/ac/sejong/web/dto/TrackJudgeAllViewDto.java
  src/main/java/kr/ac/sejong/web/dto/TrackSubjectJoinDto.java
  src/main/java/kr/ac/sejong/web/dto/UnivTrackRuleDegreeJoinDto.java
  src/main/java/kr/ac/sejong/web/dto/notice/NoticeRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/notice/NoticeResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/track/TrackRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/TrackStatisticDto.java
  src/main/java/kr/ac/sejong/web/dto/univ/UnivResponseDto.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/trackJudge.jsp
  src/test/java/kr/ac/sejong/MemberTest.java
  src/test/java/kr/ac/sejong/RuleTest.java
  src/test/java/kr/ac/sejong/TrackCourseTest.java
  src/test/java/kr/ac/sejong/TrackJudgeTest.java
  src/test/java/kr/ac/sejong/TrackTest.java
Labels: cleanup, feature

#192 [CLN, ENH] 트랙 판정시 이수율이 100%가 넘는 오류 수정, 이수율로 그래프 색상을 반환하는 기능 추가
  pom.xml
  src/main/java/kr/ac/sejong/web/dto/trackjudge/CourseStatisticDto.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/TrackStatisticDto.java
  src/test/java/kr/ac/sejong/TrackJudgeTest.java
Labels: bug, feature

#194 BUG : Invalid source release 9 Error Fix
  pom.xml
  src/main/java/kr/ac/sejong/domain/track/TrackCustomRepository.java
  src/main/java/kr/ac/sejong/domain/track/TrackRepositoryImpl.java
  src/main/java/kr/ac/sejong/service/SelectBoxService.java
Labels: bug

#197 ENH : 전체트랙 조회시 해당 대학에 존재하는 모든 CourseType을 반환하는 기능 추가
  src/main/java/kr/ac/sejong/domain/rule/RuleCustomRepository.java
  src/main/java/kr/ac/sejong/domain/rule/RuleRepositoryImpl.java
  src/main/java/kr/ac/sejong/domain/trackcourse/TrackCourseCustomRepository.java
  src/main/java/kr/ac/sejong/service/TrackAllService.java
  src/main/java/kr/ac/sejong/service/TrackRuleService.java
  src/main/java/kr/ac/sejong/web/ApiTrackAllController.java
  src/main/resources/data.sql
Labels: feature, major

#200 BUG : 트랙 판정시 이수율이 0% 나오는 오류 수정, 이전 성적표 세션에서 삭제
  src/main/java/kr/ac/sejong/domain/course/Course.java
  src/main/java/kr/ac/sejong/domain/trackJudge/TrackJudge.java
  src/main/java/kr/ac/sejong/web/TrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/CourseStatisticDto.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/TrackStatisticDto.java
  src/main/resources/data.sql
Labels: bug

#202 BUG : 트랙 규칙 학점 합산 오류 수정
  src/main/java/kr/ac/sejong/domain/trackJudge/TrackJudge.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/TrackStatisticDto.java
Labels: bug

#203 [DOC] 기이수성적 테스트케이스(HCI) 추가
  doc/테스트케이스/기이수성적-HCI-0.xls
  doc/테스트케이스/기이수성적-HCI-100.xls
  doc/테스트케이스/기이수성적-HCI-33.3.xls
  doc/테스트케이스/기이수성적-HCI-55.5.xls
Labels: doc

#206 ENH : 트랙 판정 결과 Json에 track, univ 정보 추가
  src/main/java/kr/ac/sejong/domain/trackJudge/PercentColorEnum.java
  src/main/java/kr/ac/sejong/domain/trackJudge/TrackJudge.java
  src/main/java/kr/ac/sejong/service/TrackAllService.java
  src/main/java/kr/ac/sejong/service/TrackJudgeService.java
  src/main/java/kr/ac/sejong/web/ApiTrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/CourseStatistic.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/TrackStatistic.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/TrackStatisticDto.java
  src/main/resources/data.sql
  src/test/java/kr/ac/sejong/TrackJudgeTest.java
  src/test/resources/testCardReport.xls
Labels: feature

#208 BUG : Rule에서 학위검색시 결과가 학사하나만 나오는 오류 수정
  src/main/java/kr/ac/sejong/domain/degree/Degree.java
  src/main/java/kr/ac/sejong/domain/rule/RuleCustomRepository.java
  src/main/java/kr/ac/sejong/domain/rule/RuleRepositoryImpl.java
  src/main/java/kr/ac/sejong/service/SelectBoxService.java
  src/test/java/kr/ac/sejong/RuleTest.java
Labels: bug

#209 ENH : trackJudge, uploadForm jsp
  src/main/java/kr/ac/sejong/web/IndexController.java
  src/main/webapp/WEB-INF/views/test.jsp
  src/main/webapp/WEB-INF/views/trackJudge.jsp
  src/main/webapp/WEB-INF/views/uploadForm.jsp
Labels: design

#212 BUG : PercentColor에서 색상 반환시 경계 값(100%, 50%, 25%)이 항상 RED 색상이 반환되는 오류 수정
  src/main/java/kr/ac/sejong/domain/trackJudge/PercentColorEnum.java
Labels: bug
