Repository riyenas0925/Sejong_Track_Management, pull requests merged in 2020-05, with the labels that each got.

#239 ENH : 자신이 선택한 트랙외에도 다른 트랙의 이수율을 판정하는 기능 구현
  src/main/java/kr/ac/sejong/service/TrackJudgeService.java
  src/main/java/kr/ac/sejong/service/TrackRuleService.java
  src/main/java/kr/ac/sejong/web/ApiTrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/rule/RuleResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/TrackStatisticSummary.java
  src/test/java/kr/ac/sejong/RuleTest.java
Labels: feature

#240 ENH : 허용 용량을 넘어선 파일 첨부시 에러 발생 기능 구현
  src/main/java/kr/ac/sejong/global/GlobalExceptionHandler.java
  src/main/java/kr/ac/sejong/global/exception/ErrorCode.java
  src/main/resources/develop/application-h2.properties
Labels: feature

#242 [CLN] joinView : college(단과대학), Major(학과) 필드 만듦
  src/main/java/kr/ac/sejong/config/auth/CustomUserDetailsService.java
  src/main/java/kr/ac/sejong/domain/member/Member.java
  src/main/webapp/WEB-INF/views/member/joinView.jsp
  src/test/java/kr/ac/sejong/MemberTest.java
Labels: cleanup

#243 ENH : UIS 인증후 id, pw, 소속대학과 학과를 반환하도록 변경
  src/main/java/kr/ac/sejong/config/auth/UISAuthService.java
  src/main/java/kr/ac/sejong/web/dto/uis/UISLoginResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/uis/UISUserInfoResponseDto.java
  src/test/java/kr/ac/sejong/UISAuthTest.java
Labels: feature

#244 [TEST, CLN,ENH] 로그수정- 판정 기록 대상 전체로 확대
  src/main/java/kr/ac/sejong/service/JudgeLogService.java
  src/main/java/kr/ac/sejong/service/TrackJudgeService.java
  src/main/java/kr/ac/sejong/web/ApiJudgeLogController.java
  src/main/java/kr/ac/sejong/web/ApiTrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/JudgeLogRequestDto.java
  src/main/webapp/WEB-INF/views/trackJudge.jsp
  src/test/java/kr/ac/sejong/JudgeLogTest.java
Labels: cleanup, feature

#246 BUG : 모바일에서 로그아웃이 안되는 오류 수정
  src/main/webapp/WEB-INF/views/include/sidebar.jsp
Labels: bug

#245 BUG, ENH, TST : 전체 트랙 판정 결과가 업데이트되지 않는 오류 수정, 테스트 코드 수정
  src/main/java/kr/ac/sejong/domain/trackJudge/JudgeLog/JudgeLog.java
  src/main/java/kr/ac/sejong/service/JudgeLogService.java
  src/main/java/kr/ac/sejong/web/ApiJudgeLogController.java
  src/main/java/kr/ac/sejong/web/ApiTrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/JudgeLogRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/JudgeLogResponseDto.java
  src/test/java/kr/ac/sejong/JudgeLogTest.java
Labels: bug

#249 ENH : 프론트엔드 수정 요청사항
  src/main/webapp/WEB-INF/views/include/sidebar.jsp
  src/main/webapp/WEB-INF/views/member/joinView.jsp
  src/main/webapp/WEB-INF/views/member/modifyView.jsp
  src/main/webapp/WEB-INF/views/trackAll.jsp
  src/main/webapp/WEB-INF/views/trackJudge.jsp
Labels: design

#252 ENH, CLN : TrackAll 리펙토링, 스프링 부트 캐시 적용, TrackCourse의 N+1 문제 해결
  pom.xml
  src/main/java/kr/ac/sejong/SejongtrackApplication.java
  src/main/java/kr/ac/sejong/domain/course/Course.java
  src/main/java/kr/ac/sejong/domain/trackcourse/TrackCourse.java
  src/main/java/kr/ac/sejong/domain/trackcourse/TrackCourseRepositoryImpl.java
  src/main/java/kr/ac/sejong/service/TrackAllService.java
  src/main/java/kr/ac/sejong/service/TrackRuleService.java
Labels: cleanup, feature

#253 ENH : main page update css
  src/main/java/kr/ac/sejong/web/dto/trackjudge/JudgeLogResponseDto.java
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/include/footer.jsp
  src/main/webapp/WEB-INF/views/include/header.jsp
  src/main/webapp/WEB-INF/views/include/setting-h.jsp
  src/main/webapp/WEB-INF/views/notice.jsp
  src/main/webapp/WEB-INF/views/trackJudge.jsp
  src/main/webapp/resources/img/brand/sejong.png
  src/main/webapp/resources/img/brand/sejongtrack1_blue.png
  src/main/webapp/resources/img/icons/sejong.png
Labels: design

#255 ENH : Jenkins용 kill_process.sh 추가, 배포 방식 jar에서 war로 변경
  pom.xml
  script/kill_process.sh
  src/main/java/kr/ac/sejong/SejongtrackApplication.java
Labels: feature
