Repository riyenas0925/Sejong_Track_Management, pull requests merged in 2020-04, with the labels that each got.

#215 ENH : 세종대학교 학생 인증을 위한 UIS 로그인 기능 구현
  pom.xml
  src/main/java/kr/ac/sejong/service/UISAuthService.java
  src/main/java/kr/ac/sejong/web/ApiUISAuthController.java
  src/main/java/kr/ac/sejong/web/dto/uis/UISLoginRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/uis/UISLoginResponseDto.java
  src/test/java/kr/ac/sejong/UISAuthTest.java
Labels: feature

#216 ENH : 회원가입에 uis인증 jsp 업데이트
  src/main/webapp/WEB-INF/views/member/confirm.jsp
  src/main/webapp/WEB-INF/views/member/joinView.jsp
Labels: design

#218 BUG : UIS에서 가져온 학생이름 뒤에 "_님"이 붙는 오류 수정
  src/main/java/kr/ac/sejong/config/auth/UISAuthService.java
  src/main/java/kr/ac/sejong/web/ApiUISAuthController.java
  src/main/java/kr/ac/sejong/web/dto/uis/UISLoginResponseDto.java
  src/test/java/kr/ac/sejong/UISAuthTest.java
Labels: bug

#226 [ENH] JudgeLog(멤버가 트랙조회한 기록) 엔티티 생성
  src/main/java/kr/ac/sejong/domain/member/Member.java
  src/main/java/kr/ac/sejong/domain/track/Track.java
  src/main/java/kr/ac/sejong/domain/trackJudge/JudgeLog/JudgeLog.java
Labels: feature

#229 ENH : Excel 파일만 첨부할수 있도록 Custom Valid Anotation추가, GlobalExceptionHandler로 스프링 예외처리 기능 추가
  pom.xml
  src/main/java/kr/ac/sejong/global/ErrorResponse.java
  src/main/java/kr/ac/sejong/global/GlobalExceptionHandler.java
  src/main/java/kr/ac/sejong/global/exception/ErrorCode.java
  src/main/java/kr/ac/sejong/web/TrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/excel/ExcelFileRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/excel/OnlyExcelFile.java
  src/main/java/kr/ac/sejong/web/dto/excel/OnlyExcelFileValidator.java
  src/main/java/kr/ac/sejong/web/exception/CommonExceptionAdvice.java
  src/main/webapp/WEB-INF/views/exception.jsp
  src/main/webapp/WEB-INF/views/uploadForm.jsp
Labels: feature

#231 [ENH] JudgeLog service(updateOrInsert, find) 작성
  src/main/java/kr/ac/sejong/domain/track/Track.java
  src/main/java/kr/ac/sejong/domain/trackJudge/JudgeLog/JudgeLog.java
  src/main/java/kr/ac/sejong/domain/trackJudge/JudgeLog/JudgeLogCustomRepository.java
  src/main/java/kr/ac/sejong/domain/trackJudge/JudgeLog/JudgeLogRepository.java
  src/main/java/kr/ac/sejong/domain/trackJudge/JudgeLog/JudgeLogRepositoryImpl.java
  src/main/java/kr/ac/sejong/service/JudgeLogService.java
  src/main/java/kr/ac/sejong/web/ApiTrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/course/CourseResponseDto.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/JudgeLogDto.java
  src/main/resources/data.sql
  src/test/java/kr/ac/sejong/JudgeLogTest.java
Labels: feature

#234 Delete security_message.properties
  out/artifacts/Project_Sejong_Track_Management_Web_exploded/WEB-INF/classes/security_message.properties
Labels: cleanup

#235 ENH : TrackStatistic 트랙 이수, 미이수 유무 확인을 위해 TrackJudge.PNP 변수 추가
  src/main/java/kr/ac/sejong/domain/trackJudge/TrackJudge.java
  src/main/java/kr/ac/sejong/web/ApiTrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/TrackStatistic.java
  src/main/webapp/WEB-INF/views/uploadForm.jsp
Labels: feature

#236 [CLN,ENH,Help] members_judgelogs 테이블 잘못 생성, 로그 컨트롤러 작성
  src/main/java/kr/ac/sejong/domain/member/Member.java
  src/main/java/kr/ac/sejong/domain/trackJudge/JudgeLog/JudgeLogRepository.java
  src/main/java/kr/ac/sejong/domain/trackJudge/JudgeLog/JudgeLogRepositoryImpl.java
  src/main/java/kr/ac/sejong/service/JudgeLogService.java
  src/main/java/kr/ac/sejong/web/ApiJudgeLogController.java
  src/main/java/kr/ac/sejong/web/ApiTrackJudgeController.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/JudgeLogRequestDto.java
  src/main/java/kr/ac/sejong/web/dto/trackjudge/JudgeLogResponseDto.java
  src/test/java/kr/ac/sejong/JudgeLogTest.java
Labels: cleanup, feature, help wanted
